version: "3"
services:
  hub:
    image: selenium/hub:4.15
      
  chrome:
    image: selenium/node-chrome:4.15
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.15
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  cucumberbdd:
    image:  attbatch1/buildimagethroughjenkins
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
    volumes:
      - ./testcaseoutput/cucumberreport:/home/selenium-docker/target/cucumber-reports
  
